bucklescript_init:
	cd bucklescript && npm install && npm install bs-platform

bucklescript_dev:
	cd bucklescript && node_modules/.bin/bsb -clean-world -make-world -w

bucklescript_bundle:
	cd bucklescript && rollup -c